name: realtime-mongo-server

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongo_server
    volumes:
      - ./mongodb:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    ports:
      - 27017:27017
    command: ["mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0"]
    healthcheck:
      test: test $$(echo "rs.status()" | mongo localhost:27017) -eq 0
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  redis:
  mongodb: