name: Publish Package

on:
  workflow_call:
    inputs:
      target:
        description: 'Package Target'
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    if: startsWith(github.event.release.tag_name, inputs.target)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/${{ inputs.target }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '9'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install
        shell: bash

      - name: Build Package
        run: pnpm build
        shell: bash

      - name: Set up NPM authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}