name: Publish NestJS Package

on:
  release:
    types:
      - published

jobs:
  publish:
    if: startsWith(github.event.release.tag_name, 'nestjs')
    name: NestJS
    uses: ./.github/workflows/_publish.yaml
    with:
      target: nestjs
    secrets:
      DOTENV_KEY: ${{ secrets.NPM_TOKEN }}