name: Publish Client Package

on:
  release:
    types:
      - published

jobs:
  publish:
    if: startsWith(github.event.release.tag_name, 'client')
    name: Client
    uses: ./.github/workflows/_publish.yaml
    with:
      target: client
    secrets:
      DOTENV_KEY: ${{ secrets.NPM_TOKEN }}